live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"

[colors.cursor]
text = "0x0d1117"
cursor = "0xc9d1d9"

[colors.normal]
black = "0x484f58"
red = "0xff7b72"
green = "0x58a6ff"
yellow = "0xd29922"
blue = "0x58a6ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[colors.bright]
black = "0x6e7681"
red = "0xffa198"
green = "0x79c0ff"
yellow = "0xe3b341"
blue = "0x79c0ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
# builtin_box_drawing = false
size = 12.6

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "ComicCode Nerd Font SemiBold"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 30

[window.padding]
x = 0
y = 0
